In [1]:
import numpy as np

In [5]:
probabilities = np.random.rand(10, 10)
probabilities = probabilities / probabilities.sum(axis=0, keepdims=True)
probabilities


array([[0.04157307, 0.11244532, 0.13703628, 0.06093249, 0.1247309 ,
        0.18773053, 0.14797156, 0.15027693, 0.06771301, 0.09886528],
       [0.03396711, 0.09627993, 0.11928348, 0.11784556, 0.12290203,
        0.05458398, 0.08945748, 0.0884285 , 0.16934491, 0.1003782 ],
       [0.17280832, 0.12889193, 0.06304792, 0.10715373, 0.11033363,
        0.00396877, 0.12271199, 0.15330509, 0.16172778, 0.11469711],
       [0.11844028, 0.12509705, 0.12048532, 0.08803767, 0.15776943,
        0.08609232, 0.03615707, 0.07963092, 0.14711808, 0.06999737],
       [0.10344644, 0.12756486, 0.0659541 , 0.02268821, 0.03018309,
        0.17618903, 0.00627778, 0.12739888, 0.01334217, 0.12532313],
       [0.09815585, 0.10724887, 0.03248262, 0.12878669, 0.04161577,
        0.0244689 , 0.21386113, 0.15421197, 0.10517151, 0.13374146],
       [0.04671575, 0.0449169 , 0.0838187 , 0.16127773, 0.08490846,
        0.18681208, 0.10211416, 0.03814071, 0.04476548, 0.06410714],
       [0.15286575, 0.12227659, 0.2439108

In [6]:
accumulated_sum = np.cumsum(probabilities, axis=0)
accumulated_sum

array([[0.04157307, 0.11244532, 0.13703628, 0.06093249, 0.1247309 ,
        0.18773053, 0.14797156, 0.15027693, 0.06771301, 0.09886528],
       [0.07554019, 0.20872524, 0.25631976, 0.17877805, 0.24763293,
        0.24231451, 0.23742904, 0.23870543, 0.23705791, 0.19924347],
       [0.24834851, 0.33761718, 0.31936768, 0.28593178, 0.35796656,
        0.24628328, 0.36014103, 0.39201052, 0.3987857 , 0.31394058],
       [0.36678879, 0.46271423, 0.43985299, 0.37396945, 0.51573599,
        0.3323756 , 0.3962981 , 0.47164145, 0.54590377, 0.38393795],
       [0.47023523, 0.59027908, 0.5058071 , 0.39665766, 0.54591908,
        0.50856463, 0.40257588, 0.59904032, 0.55924594, 0.50926108],
       [0.56839109, 0.69752795, 0.53828971, 0.52544434, 0.58753486,
        0.53303354, 0.61643701, 0.75325229, 0.66441745, 0.64300254],
       [0.61510684, 0.74244485, 0.62210841, 0.68672207, 0.67244331,
        0.71984562, 0.71855118, 0.791393  , 0.70918293, 0.70710968],
       [0.76797259, 0.86472143, 0.8660192

In [15]:
a = accumulated_sum[:, 0]
a

array([0.04157307, 0.07554019, 0.24834851, 0.36678879, 0.47023523,
       0.56839109, 0.61510684, 0.76797259, 0.87523086, 1.        ])

In [20]:
index = np.where(a > 0.5)[0][0]
index

np.int64(5)